table AMZN
	lineageTag: 65db9cc3-22ec-4804-b78c-9f267e3c431b

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7abf3ba3-a4e1-4836-886f-bbd93d7b0376
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: f0b60dc5-f75d-4131-9a87-a2519851e945
			defaultHierarchy: LocalDateTable_9a205173-b345-4392-a144-e7610fe48f24.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: cf9ee136-1990-4006-840f-a12d0913aee6
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 824acd9f-77f5-4b8f-a131-7946e462e0e4
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 7271f0e9-32aa-49bb-82e7-6cb8729d60fc
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: d1c923fc-068c-4601-a5d0-4f38daaf42fc
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: d75a9f6b-2f3b-4c5e-b3cb-c0d05038a77c
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 8ccb80a2-283e-4b94-9633-0edb4d25d9f0
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jolale3\Downloads\archive\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

